<?php

namespace Href\ShortyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsRepository extends EntityRepository
{
}
