<?php

namespace Href\ShortyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository
{
    public function getTopTen()
    {
        $query = $this->createQueryBuilder('s')
            ->orderBy('u.count', 'DESC')
            ->setMaxResults(10)
            ->getQuery();

        return $query->getResult();
    }

    public function getLastTen()
    {
        $query = $this->createQueryBuilder('u')
            ->orderBy('u.created', 'DESC')
            ->setMaxResults(10)
            ->getQuery();

        return $query->getResult();
    }

    public function getSortedByDate($user_id)
    {
        return $this->createQueryBuilder('url')
            ->leftJoin('url.user', 'user')
            ->where('user.id = :id')
            ->setParameter('id', $user_id)
            ->orderBy('url.created', 'DESC')
            ->getQuery()->getResult();
    }
}
