<?php

namespace Href\ShortyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository
{
    public function getTopTen()
    {
        $query = $this->createQueryBuilder('s')
            ->orderBy('u.count', 'DESC')
            ->setMaxResults(10)
            ->getQuery();

        return $query->getResult();
    }
}
