imports:
    - { resource: config_dev.yml }

doctrine:
  dbal:
    driver: pdo_sqlite
    path:  %kernel.cache_dir%/test.db

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
