url_new:
    pattern: /
    defaults: { _controller: HrefShortyBundle:Shorty:index }

url_success:
    pattern: /success/{generated}
    defaults:
      _controller: HrefShortyBundle:Shorty:success

url_api:
    pattern: /api
    defaults:
      _controller: HrefShortyBundle:Shorty:api

url_bookmarklet:
    pattern: /bookmarklet
    defaults:
      _controller: HrefShortyBundle:Shorty:bookmarklet

url_show:
    pattern: /{generated}/{mode}
    defaults:
      _controller: HrefShortyBundle:Shorty:show
      mode: show

url_pages_tweetbot:
    pattern: /pages/instructions/tweetbot
    defaults:
      _controller: HrefShortyBundle:Shorty:tweetbot

url_pages_bookmarklet:
    pattern: /pages/instructions/bookmarklet
    defaults:
      _controller: HrefShortyBundle:Shorty:bookmarkletPage