url_profile_links:
    pattern: /profile/links
    defaults:
      _controller: HrefShortyBundle:User:profile
url_admin:
    pattern: /admin
    defaults:
      _controller: HrefShortyBundle:Admin:index

url_new:
    pattern: /
    defaults: { _controller: HrefShortyBundle:Shorty:index }

url_success:
    pattern: /success/{generated}
    defaults:
      _controller: HrefShortyBundle:Shorty:success

url_api:
    pattern: /api
    defaults:
      _controller: HrefShortyBundle:Shorty:api

url_bookmarklet:
    pattern: /bookmarklet
    defaults:
      _controller: HrefShortyBundle:Shorty:bookmarklet

url_jsonp:
    pattern: /jsonp
    defaults:
      _controller: HrefShortyBundle:Shorty:jsonp
    options:
      expose: true

url_show:
    pattern: /{generated}/{mode}
    defaults:
      _controller: HrefShortyBundle:Shorty:show
      mode: show

url_pages_tweetbot:
    pattern: /pages/instructions/tweetbot
    defaults:
      _controller: HrefShortyBundle:Shorty:tweetbot

url_pages_bookmarklet:
    pattern: /pages/instructions/bookmarklet
    defaults:
      _controller: HrefShortyBundle:Shorty:bookmarkletPage

